routes/web.php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
	return view('welcome');
});


// Rutas de Paises, Estados y Ciudades
Route::get('/countries', [CountryController::class, 'index']);
Route::get('/provinces-by-country/{id}', [ProvinceController::class, 'getProvicesByCountry']);
Route::get('/cities-by-province/{id}', [CityController::class, 'getCitiesByProvice']);

Auth::routes();
// Ruta de inicio
Route::get('/dashboard', [HomeController::class, 'index'])->name('home');

Route::get('/mails', [MailController::class, 'index'])->name('mails');
Route::get('/mails/create', [MailController::class, 'create'])->name('mails.create');
Route::post('/mails', [MailController::class, 'store'])->name('mails.store');

// Rutas de usuarios
Route::resource('/users', UserController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Carbon\Carbon;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'surnames',
        'phone',
        'identification_number',
        'birthdate',
        'role',
        'city_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
        'age'
    ];

    /**
     * Function calculate age user.
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    public function getAgeAttribute()
    {
        $today = Carbon::now();

        return Carbon::parse($this->birthdate)->age;
    }

    /**
    * Relation user with city.
    */
    public function city()
    {
        return $this->hasOne(City::class, 'id', 'city_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use Illuminate\Support\Facades\Hash;
use App\Helpers\Helper;

class UserController extends Controller
{
    public function __construct(Helper $helper)
    {
        $this->helper = $helper;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = User::with('city');

        if($request->search) {
            $search = $request->search;

            $query = $query->where('name', 'LIKE' ,'%'. $search . '%')
                    ->orWhere('surnames', 'LIKE' ,'%'. $search . '%')
                    ->orWhere('identification_number', 'LIKE' ,'%'. $search . '%')
                    ->orWhere('email', 'LIKE' ,'%'. $search . '%')
                    ->orWhere('phone', 'LIKE' ,'%'. $search . '%');
        }

        $field = 'id';

        if($request->field) {
            $field = $request->field;
        }

        $sort = 'asc';

        if($request->sort) {
            $sort = $request->sort;
        }

        $query = $query->orderBy($field, $sort);

        $users = $query->paginate(10);

        if($request->ajax()){
           return [
                'users' => view('users.partial')->with(compact('users'))->render(),
                'next_page' => $users->nextPageUrl()
            ];
        }

        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $data = $request->all();

        // Encripta el password
        $data['password'] = Hash::make($data['password']);
        //Asigna Rol
        $data['role'] = 'user';

        User::create($data);

        return redirect()->route('users.index')->with('success','Usuario creado correctamente.');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $data = $request->all();

        $user = User::find($id);

        $user->update($data);

        $this->helper->user_log('Editando registro ' . $id);

        if($request->ajax()){
            return response()->json('Usuario actualizado');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        User::where('id', $id)->delete();

        $this->helper->user_log('Eliminando registro ' . $id);

        if($request->ajax()){
            return response()->json('Usuario eliminado');
        }

    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', 'Crear Usuario')
@section('content')
	<div class="ml-4 mr-4">
		<div class="card">
			<div class="card-body">
		    	<h1 class="card-title text-center">Crear Usuario</h1>

		    	<div>
				<form action="{{ route('users.store') }}" method="POST" >
					<input type="hidden" name="_token" value="{{ csrf_token() }}">
					<input type="hidden" name="city_id" id="city_id" value="">

					<div class="form-row">
				    	<div class="form-group col-md-6">
				      		 <label for="names" class="control-label">
								Nombres
							</label>
							<input type="text" class="form-control" name="name" id="name" value="{{ old('names') }}" required>
							@error('names')
							    <small class="text-danger">{{ $message }}</small>
							@enderror
				    	</div>
					    <div class="form-group col-md-6">
					    	<label for="surnames" class="control-label">
								Apellidos
							</label>
							<input type="text" class="form-control" name="surnames" id="surnames" value="{{ old('surnames') }}" required>
							@error('surnames')
							    <small class="text-danger">{{ $message }}</small>
							@enderror
					    </div>
				  	</div>

					<div class="form-row">
					    <div class="form-group col-md-4">
					    	<label for="email" class="control-label">
								Correo Electronico
							</label>
							<input type="email" class="form-control" name="email" id="email" value="{{ old('email') }}" required>
							@error('email')
							    <small class="text-danger">{{ $message }}</small>
							@enderror
					    </div>

					    <div class="form-group col-md-4">
					    	<label for="identification_number" class="control-label">
								Documento de Identificacion
							</label>
							<input type="text" class="form-control" name="identification_number" id="identification_number" value="{{ old('identification_number') }}" required>
							@error('identification_number')
							    <small class="text-danger">{{ $message }}</small>
							@enderror
					    </div>

					     <div class="form-group col-md-4">
					    	<label for="password" class="control-label">
								Contraseña
							</label>
							<input type="password" class="form-control" name="password" id="password" value="{{ old('password') }}" required>
							@error('password')
							    <small class="text-danger">{{ $message }}</small>
							@enderror
					    </div>
					</div>
					<div class="form-row">
					    <div class="form-group col-md-4">
					    	<label for="phone" class="control-label">
								Telefono
							</label>
							<input type="text" min="8" max="11" class="form-control" name="phone" id="phone" value="{{ old('phone') }}" required>
							@error('phone')
							    <small class="text-danger">{{ $message }}</small>
							@enderror
					    </div>
					    <div class="form-group col-md-4">
					    	<label for="birthdate" class="control-label">
								Fecha de Nacimiento
							</label>
							<input type="date" max="<?php echo date("Y-m-d",strtotime(date("Y-m-d")."- 15 year"));?>" class="form-control" name="birthdate" id="birthdate" value="{{ old('birthdate') }}" required>
							@error('birthdate')
							    <small class="text-danger">{{ $message }}</small>
							@enderror
					    </div>
					    <div class="form-group col-md-4">
					    	<label for="age" class="control-label">
								Edad
							</label>
							<input type="text" disabled class="form-control" name="age" id="age" value="{{ old('age') }}">
					    </div>
					</div>
					<div class="form-row">
					    <div class="form-group col-md-4">
					    	<label for="countries" class="control-label">
								Pais
							</label>
							<select class="form-control" value="{{ old('countries') }}" name="countries" id="countries">
								<option>Seleccione un pais</option>
							</select>
					    </div>
					    <div class="form-group col-md-4">
					    	<label for="provinces" class="control-label">
								Estado
							</label>
							<select class="form-control" value="{{ old('provinces') }}" name="provinces" id="provinces">
							</select>
					    </div>
					    <div class="form-group col-md-4">
					    	<label for="cities" class="control-label">
								Ciudad
							</label>
							<select class="form-control" value="{{ old('cities') }}" name="cities" id="cities">
							</select>
							@error('city_id')
							    <div class="alert alert-danger">{{ $message }}</div>
							@enderror
					    </div>
					</div>
					<div class="form-row">
						<div class="form-group text-right col-md-12">
							<a href="{{ route('users.index') }}" class="btn btn-danger">Volver</a>
							<button type="submit" class="btn btn-success">Guardar</button>

						</div>
					</div>
				</form>
		  </div>
		</div>
	</div>
@endsection

@section('js')
	<script src="{{asset('js/admin/create-user.js?code='.rand(0,9999))}}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" crossorigin="anonymous"></script>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', 'Listado de Usuario')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card mb-4">
		    	<div class="card-header">Listado de Usuarios</div>

		    	<div class="ml-3 mb-3 mt-5">
		    		<a href="{{ route('users.create') }}" class="btn btn-success">Crear Usuario</a>
		    	</div>

		    	<div class="input-group">
			    	<div class="col-md-6 input-group">
			    		<label><strong>Ordenar:</strong></label>
			    		<select id="fieldby" class="form-control ml-3">
			    			<option value="null">Seleccionar Campo</option>
			    			<option value="name">Nombres</option>
			    			<option value="surnames">Apellidos</option>
			    			<option value="email">Correo Electronico</option>
			    			<option value="identification_number">Numero de identificacion</option>
			    			<option value="birthdate">Fecha de Nacimiento</option>
			    			<option value="age">Edad</option>
			    		</select>
			    		<select id="orderby" class="form-control ml-3">
			    			<option value="null">Seleccionar Orden</option>
			    			<option value="asc">Ascendente</option>
			    			<option value="desc">Descendente</option>
			    		</select>
			    		<div>
				    		<button class="btn btn-primary ml-2" id="order-list">
	                            Ordenar
	                        </button>
			    		</div>
			    	</div>
			    	<div class="col-md-2">
			    	</div>
			    	<div class="mx-auto mb-3 col-md-4">
			    		<form action="{{ route('users.index') }}" method="GET" role="search">
				    		<div class="input-group">
		                        <input type="text" class="form-control mr-2" name="search" id="search" value="{{ old('search') }}">
	                            <button class="btn btn-info mr-2" type="submit" title="Buscar">
	                                Buscar
	                            </button>
		                        <a href="{{ route('users.index') }}" class="btn btn-danger">Resetear</a>
		                    </div>
	                	</form>
			    	</div>
		    	</div>
		    	<div>
		    		@include('notifications.success')
		    	</div>
		    	@include('users.partial')

		    </div>
		</div>
	</div>
</div>
@endsection

@section('js')
	<script src="{{asset('js/admin/index-user.js?code='.rand(0,9999))}}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" crossorigin="anonymous"></script>
@endsection

resources/views/users/partial.blade.php
<div>
	<table class="table table-bordered" width="100%" id="list-user">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nombres</th>
				<th>Apellidos</th>
				<th>Correo Electronico</th>
				<th>Documento de Identificacion</th>
				<th>Telefono</th>
				<th>Fecha de Nacimiento</th>
				<th>Edad</th>
				<th>Ciudad</th>
				<th>Opciones</th>
			</tr>
		</thead>
		<tbody>
			@foreach($users as $user)
				<tr class="item{{$user->id}}">
					<td>{{$user->id}}</td>
					<td>
						<input type="hidden" name="edit" value="0" id="edit">
						<input type="text" class="form-control" name="name" value="{{$user->name}}" readonly id="names-{{$user->id}}">
					</td>
					<td>
						<input type="text" class="form-control" name="surnames" value="{{$user->surnames}}" readonly id="surnames-{{$user->id}}">
					</td>
					<td>
						<input type="email" class="form-control" name="email" value="{{$user->email}}" readonly id="email-{{$user->id}}">
					</td>
					<td>
						<input type="text" class="form-control" name="identification_number" value="{{$user->identification_number}}"  id="identification_number-{{$user->id}}" readonly>
					</td>
					<td>
						<input type="text" class="form-control" name="phone" value="{{$user->phone}}"  id="phone-{{$user->id}}" readonly>
					</td>
					<td>
						<input type="date" class="form-control"  name="birthdate" value="{{$user->birthdate}}" max="<?php echo date("Y-m-d",strtotime(date("Y-m-d")."- 15 year"));?>" id="birthdate-{{$user->id}}" readonly>
					</td>
					<td>
						<label id="age-{{$user->id}}">
							{{$user->age}}
						</label>
					</td>
					<td>{{$user->city['name']}}</td>
					<td>
						<div class="input-group">
							<button class="btn btn-warning btn-sm mb-1" id="edit-user-{{$user->id}}" onClick="editUser({{$user->id}})">Editar</button>
							<button class="btn btn-danger btn-sm" id="delete-user-{{$user->id}}" onClick="deleteUser({{$user->id}})">Eliminar</button>
						</div>
					</td>
				</tr>
			@endforeach
			@if(count($users) == 0)
				<tr class="text-center">
					<td colspan="10"><h2>No existe usuario</h2></td>
				</tr>
			@endif
		</tbody>
	</table>

	<div class="row">
		<div class="mx-auto pull-right">
			{{ $users->links() }}
		</div>
	</div>
</div>